### ISSUE TITLE
Not properly fetching ClassOfClassOfSpatioTemporalExtent

### ISSUE THREAD

**Issue by Fabalab** [gchq/MagmaCore#221]
**Describe the bug**
ClassOfClassOfSpatioTemporalExtent is being fetched as a ClassOfSpatioTemporalExtent so that when it is cast, a ClassCastException is being thrown.

**To Reproduce**
Run the following code:
```
public class Program {
	public static void main(String[] args) {
		final MagmaCoreService mcService = MagmaCoreServiceFactory.createWithJenaDatabase();
		
		final IriBase testIriBase = new IriBase("test", "https://example.com/test#");
		final IRI testIri = new IRI(testIriBase, "TestClassOfClassOfSpatioTemporalExtent");
		
		final ClassOfClassOfSpatioTemporalExtent testClassOfClassOfSpatioTemporalExtent = new ClassOfClassOfSpatioTemporalExtentBuilder(testIri).build();
		
		mcService.create(testClassOfClassOfSpatioTemporalExtent);
		
		final ClassOfClassOfSpatioTemporalExtent retrievedClassOfClassOfSpatioTemporalExtent = (ClassOfClassOfSpatioTemporalExtent) mcService.get(testIri);
	}
}
```

Which spits out the following error:
```
Exception in thread "main" java.lang.ClassCastException: class uk.gov.gchq.magmacore.hqdm.model.impl.ClassOfSpatioTemporalExtentImpl cannot be cast to class uk.gov.gchq.magmacore.hqdm.model.ClassOfClassOfSpatioTemporalExtent (uk.gov.gchq.magmacore.hqdm.model.impl.ClassOfSpatioTemporalExtentImpl and uk.gov.gchq.magmacore.hqdm.model.ClassOfClassOfSpatioTemporalExtent are in unnamed module of loader 'app')
	at uk.co.amrc.adg23537.Program.main(Program.java:38)
```

**Expected behavior**
This should run with no errors or output.

**Additional context**
Run on the current Main branch of MagmaCore

**Comment by ClimbingAl** [comment]
Just recreated error as described above.  It is cause by an error in the `HqdmObjectFactory.mapToThing(final String typeName, final IRI iri)` switch-case statement for the offending type handled in the  [`case "class_of_class_of_spatio_temporal_extent"`](https://github.com/gchq/MagmaCore/blob/69beaf85ea7c6255d12834d7d09b9e996eb3d5f4/hqdm/src/main/java/uk/gov/gchq/magmacore/hqdm/rdf/HqdmObjectFactory.java#L450).  It should return `ClassServices.createClassOfClassOfSpatioTemporalExtent(iri);` but instead returns `ClassServices.createClassOfSpatioTemporalExtent(iri);`.
I have just tested it locally and it works.  I will submit a PR later for this fix.  There is already an outstanding PR for `HqdmObjectFactory` but it also contains the error you found (see [here](https://github.com/gchq/MagmaCore/blob/84c733c87f042cc492ad68e7f195473ba8223b89/hqdm/src/main/java/uk/gov/gchq/magmacore/hqdm/rdf/HqdmObjectFactory.java#L463)).
