### ISSUE TITLE
Pattern Handling: Add an example that illustrates the 'representation by sign' pattern.

### ISSUE THREAD

**Issue by GCHQDeveloper42** [gchq/MagmaCore#3]
The separation of names from what they represent is a key benefit from extensional 4D models. It is a major feature of the HQDM model but requires careful implementation for first use. Documenting the use of the `representation_by_sign` pattern of HQDM objects would help users and could be used to implement a pattern handling feature to Magma Core code to make the adoption of `representation_by_sign` easier. An example on it's own in the Wiki may not be enough to ensure that the complex, but repeatable, pattern is used consistently.

**Comment by twalmsley** [comment]
My next PR includes an example for the use of the HQDM `sign` pattern and will resolve this issue.
