### ISSUE TITLE
Use of `http://www.semanticweb.org/` in HQDM IRIs

### ISSUE THREAD

**Issue by twalmsley** [gchq/MagmaCore#48]
Agree something different.

**Comment by ClimbingAl** [comment]
I have created a github account called hqdmTop and this comes with the associated "hqdmtop.github.io" domain.  I have used it to host the hqdmFramework (https://hqdmtop.github.io/hqdmFramework/). This domain could be used as a namespace to replace the "www.semanticweb.org" one.  I suggest something like https://hqdmtop.github.io/hqdm.
